### ISSUE TITLE
Cobigen-generated FindByCriteria behaves in unexpected way

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/tools-cobigen#844]
### Moving issue
This issue was on [devon4j](https://github.com/devonfw/devon4j/issues/69), so I decided to move it here.

When using Cobigen to generate the Entity infrastructure, it produces something like:
```
public interface AccountingEntryRepository extends DefaultRepository<AccountingEntryEntity> {

  /**
   * @param criteria the {@link AccountingEntrySearchCriteriaTo} with the criteria to search.
   * @param pageRequest {@link Pageable} implementation used to set page properties like page size
   * @return the {@link Page} of the {@link AccountingEntryEntity} objects that matched the search.
   */
  default Page<AccountingEntryEntity> findByCriteria(AccountingEntrySearchCriteriaTo criteria) {
...
```
The documented parameter `pageRequest` is apparently not part of the method's signature and is not mentioned in the generated code.
Instead, the generated `AccountingEntrySearchCriteriaTo` has a member `private Pageable pageable` from `AbstractSearchCriteriaTO`.

The documentation of that is:
```
  /**
   * @return the {@link Pageable} containing the optional pagination information or {@code null}.
   */
  public Pageable getPageable() {

    return this.pageable;
  }
``` 
However, if I call `findByCriteria()` with an `AccountingEntrySearchCriteriaTo` that has its `Pageable` not set, I receiver a Null Pointer Exception (this may be due to other problems in my code, not sure yet)

I have generated my project using devcon. I use the 3.0.0 distribution with the 20190115 patch.

**Comment by jdiazgon** [comment]
Hello @Jan-PeterRichterCG,

I would like to know in which use case you wouldn't use `Pageable`. Are you trying to get just one `AccountingEntry`?

Thanks!

**Comment by Jan-PeterRichterCG** [comment]
@jdiazgon: "I would like to know in which use case you wouldn't use Pageable" Yes, I was asking myself the same question after filing the issue. My "use case" was a test case where I knew that there are just a hand full of results and I have to check them all - so I simply want to have them all and in any order.
This, however, can also be a valid use case in production. If you have a table with some master data, you know that there are just a few (because the business logic tells you that there simply cannot be hundreds of this type) and you need them all - then you don't need a pageable.

I admit that these cases will probably be rare, and if you really _need_ to have a query that _doesn't contain_ the pageable restriction (for whatever reason), then you can still write the query by hand.

So, the easiest fix for this bug would be to remove the line `@param pageRequest {@link Pageable} implementation used to set page properties like page size` and change the line `@return the {@link Pageable} containing the optional pagination information or {@code null}.` to `@return the {@link Pageable} containing the pagination information.` from the templates. ==> no more false java docs generated!

**Comment by jdiazgon** [comment]
Thanks for your explanation 👍 

It is possible to set a `Pageable` object that returns all the results, I have just tried it on our method `findByCriteria(...)`:

```Java
return QueryUtil.get().findPaginated(PageRequest.of(0, Integer.MAX_VALUE), query, true);
```

The `PageRequest.of(0, Integer.MAX_VALUE)` creates a new Pageable object that retrieves all the items of your entity.

I do agree that throwing a null pointer exception when no `Pageable` is set is not a good practice. Maybe we could set on that case a default `PageRequest.of(0, Integer.MAX_VALUE)`.

Nevertheless, we should for sure change the Javadoc.

**Comment by Jan-PeterRichterCG** [comment]
@jdiazgon 
I would suggest to change the template for WhatsoeverEntityRepository.java in the following way:
- remove javadoc line `@param pageRequest {@link Pageable} implementation used to set page properties like page size`
- add something like `if(null == criteria.getPageable()) {criteria.setPageable(...)}` so that a default Pageable is added to the criteria if none is present.

The second step, however, is a bit controversial: When you call findByCriteria(), the method not only returns a result but also silently changes your criteria parameter by adding a Pageable that you have not specified. 
A truly clean solution would be 
- to make a copy of the criteria, add the default Pageable to the copy and use the augmented copy OR 
- to remove the default Pageable IF it was added within findByCriteria() before returning the result (and this should be done in a try/finally to ensure the removal even in case of an exception)   

Best Regards

Jan-Peter

**Comment by jdiazgon** [comment]
> to remove the default Pageable IF it was added within findByCriteria() before returning the result (and this should be done in a try/finally to ensure the removal even in case of an exception)

Seems valid to me. What do you think @maybeec ?

**Comment by Jan-PeterRichterCG** [comment]
Hmmmm....  looking closer into the code that is actually called, I can see an even better way:
- in `WhatsoeverRepository.findByCriteria()` there are two calls: 
   - `addOrderBy(query, alias, criteria.getPageable().getSort())` - this one crashes if getPageable() returns null
   - `QueryUtil.get().findPaginated(criteria.getPageable(), query, true)` - this one calls `QueryUtil.findPaginated(Pageable pageable, JPAQuery<E> query, boolean determineTotal)` and that calls `QueryHelper.findPaginatedGeneric(Pageable pageable, JPAQuery<E> query, boolean determineTotal)` - and that one can handle Pageables that are null
==> It would be sufficient to just enclose the call to `addOrderBy()` with an `if(null != criteria.getPageable()` and we're done!

**Comment by jdiazgon** [comment]
Good approach :)

**Comment by maybeec** [comment]
Hi @Jan-PeterRichterCG thanks for pointing this out and sry for the late reply :)
@jdiazgon could we provide a quickfix and a release of the template for that?

**Comment by jdiazgon** [comment]
> `QueryHelper.findPaginatedGeneric(Pageable pageable, JPAQuery<E> query, boolean determineTotal)` - and that one can handle Pageables that are null

I have just checked this and unfortunately pageable must not be null. Please see the following figure:

![image](https://user-images.githubusercontent.com/31688036/54920565-d34c4d00-4f03-11e9-814c-f79ea6a0462c.png)

It creates a new `PageImpl` instance which `asserts` that the pageable is not null. Therefore it throws a 500 internal server error.

So my proposal would be: If no pageable is set, then we should create a default one. This default pageable would return all the elements from the database. Do you agree?

**Comment by jdiazgon** [comment]
[Here](https://github.com/jdiazgon/tools-cobigen/commit/4c176ee020deb00993f35f6cbedc507e5f6b7377), you will find my commit with the implemented changes.

**Comment by Jan-PeterRichterCG** [comment]
The question is: is `com.devonfw.module.jpa.dataaccess.api.findPaginatedGeneric()` broken or not?
- the javadoc sais: `* @param pageable contains information about the requested page and sorting.` There is no explicit documentation about a pageable that is null
- later on in the code we find ` if (pageable != null) { ...` which indicates that the code is intended to handle null-valued `pageable` parameters 
- However, if called with a null-valued `pageable`, it crashes due to `PageImp<>()` not accepting null

A clean solution would be to
- decide whether findPaginatedGeneric() shall be able to process null-valued `pageable` parameters or not
- if yes, there should be added an `else` branch to the afore mentioned ` if (pageable != null) { ...` where the local pageable is set to the default Pageable - yielding the call to `PafeImp<>()` safe.
- if no, it should be documented in the javadoc of `findPaginatedGeneric()` that the parameter `pageable` must not be null and the ` if (pageable != null) { ...` can be deleted to make the code more staight-forward.

**Comment by jdiazgon** [comment]
> the code is devon4j...

You are right. As we have already addressed the Javadoc problem on the CobiGen template, I think I'm going to create a new issue on devon4j and not transfer this issue.
